server:
  shutdown: graceful
  tomcat:
    threads:
      max: 200 # 최대 워커 스레드 수 (default : 200)
      min-spare: 10 # 최소 유지 스레드 수 (default : 10)
    connection-timeout: 1m # 연결 타임아웃 (ms) (default : 60000ms = 1m)
    max-connections: 8192 # 최대 동시 연결 수 (default : 8192)
    accept-count: 100 # 대기 큐 크기 (default : 100)
    keep-alive-timeout: 60s # 60s
  max-http-request-header-size: 8KB

spring:
  application:
    name: runky
  profiles:
    active: local  # 기본 활성 프로필 (local or prod)
  config:
    import:
      - jpa.yml

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
springdoc:
  use-fqn: true
  swagger-ui:
    path: /swagger-ui.html

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  redirect-url: ${KAKAO_REDIRECT_URL}


runky:
  security:
    signup-token:
      ttlMinutes: ${SIGNUP_TTL}
    jwt:
      access:
        secret-key: ${JWT_ACCESS_SECRET}
        expiration-minutes: ${ACCESS_EXPIRATION}
        algorithm: ${ACCESS_ALGORITHM}
      refresh:
        secret-key: ${JWT_REFRESH_SECRET}
        expiration-minutes: ${REFRESH_EXPIRATION}
        algorithm: ${REFRESH_ALGORITHM}

    refresh-token:
      hash:
        mode: ${REFRESH_HASH_MODE}
        algorithm: ${REFRESH_HASH_ALGORITHM}
        pepper: ${REFRESH_TOKEN_PEPPER}

    cookie:
      common:
        path: "/"
        domain: ~
        http-only: true
        secure: true
        same-site: None
      access:
        name: "accessToken"
        max-age-minutes: 1440
      refresh:
        name: "refreshToken"
        max-age-minutes: 10080
      signup:
        name: "signupToken"
        max-age-minutes: 10

---
spring:
  config:
    activate:
      on-profile: local, test
kakao:
  client-id: 10591b4c28e1de84d6fd5da8ec5c3467
  redirect-url: http://localhost:8080/api/auth/login/oauth2/code/kakao


runky:
  security:
    signup-token:
      ttlMinutes: 10
    jwt:
      access:
        secret-key: accessSecret2025accessSecret2025accessSecret2025accessSecret2025
        expiration-minutes: 1440 # 24h
        algorithm: HS256
      refresh:
        secret-key: refreshSecret2025refreshSecret2025refreshSecret2025refreshSecret2025
        expiration-minutes: 10080 # 7d
        algorithm: HS256

    # RT 저장용 해시
    refresh-token:
      hash:
        mode: HMAC
        algorithm: HmacSHA256
        pepper: refreshSecret20250812refreshSecret20250812refreshSecret20250812

    cookie:
      common:
        path: "/"
        domain: ~
        http-only: true
        secure: true
        same-site: None
      access:
        name: "accessToken"
        max-age-minutes: 1440
      refresh:
        name: "refreshToken"
        max-age-minutes: 10080
      signup:
        name: "signupToken"
        max-age-minutes: 10

---
spring:
  config:
    activate:
      on-profile: prod
